flarum:
  image: mondedie/docker-flarum:0.1.0-beta.6-stable
  container_name: flarum
  links:
    - mariadb:mariadb
  ports:
    - "80:8888"
  environment:
    - FORUM_URL=http://localhost
    - DB_PASS=localdummypassword
  volumes:
    - /mnt/docker/flarum/assets:/flarum/app/assets
    - /mnt/docker/flarum/extensions:/flarum/app/extensions

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=localdummypassword
    - MYSQL_DATABASE=flarum
    - MYSQL_USER=flarum
    - MYSQL_PASSWORD=localdummypassword
